# Use an existing node alpine image as a base image
FROM node:18-alpine

# Set the working directory
WORKDIR /React-ECommerce/

# Copy the package.json file
COPY public/ /React-ECommerce/public
COPY src/ /React-ECommerce/src
COPY package.json /React-ECommerce/

# Install application dependencies
RUN npm install

# Copy the rest of the application files
COPY . .
# Expose the port
EXPOSE 3000

# Run the application
CMD ["npm", "start"]